variables:
  CI_IMAGE: quantumbrilliance/ci-ubuntu20.04:sdk-beta-13
  EMULATOR_CI_IMAGE: registry.gitlab.com/qbau/software-and-apps/emulator

stages:
  - build
  - test
  - deploy

.install-core:
  before_script:
    - echo $PWD
    - ls *
    - whoami
    - rm -rf ${QB_DIR}/core-local
    - mv core_artefacts/build .
    - cmake --install build

ubuntu20-build-for-emulator:
  stage: build
  image: $EMULATOR_CI_IMAGE
  tags: 
    - cutensornet2.0
  script:
    - rm -rf ${QB_DIR}/core-local
    # Build core with SUPPORT_EMULATOR_BUILD_ONLY=ON
    - cmake -B build . 
      -DCMAKE_INSTALL_PREFIX=${QB_DIR}/core-local 
      -DSUPPORT_EMULATOR_BUILD_ONLY=ON
      -DXACC_DIR=${QB_DIR}/xacc-local
      -DTNQVM_DIR=${QB_DIR}/xacc-local
    - cmake --build build -- -j`nproc`
    # We need to put these things in a dedicated folder to avoid clashing with files of the same name in downstream projects.
    - mkdir core_artefacts
    - mv build cmake include core_artefacts
  artifacts:
    when: always
    paths: 
      # These are all the things required to install the core for supporting the build of the emulator.
      - core_artefacts/build/cmake_install.cmake
      - core_artefacts/build/coreDependencies.cmake
      - core_artefacts/build/qbcore-config.cmake
      - core_artefacts/build/qbcore-config-version.cmake
      - core_artefacts/build/CMakeFiles/Export/
      - core_artefacts/build/libnoise.so*
      - core_artefacts/cmake/py_packages_path.cmake
      - core_artefacts/cmake/xacc_utilities.cmake
      - core_artefacts/cmake/manifest.json.in
      - core_artefacts/include
      
ubuntu20-build:
  stage: build
  image: $CI_IMAGE
  script:
    - rm -rf ${QB_DIR}/core-local
    - cmake -B build . 
      -DCMAKE_INSTALL_PREFIX=${QB_DIR}/core-local 
      -DTNQVM_DIR=${QB_DIR}/xacc-local
    - cmake --build build -- -j`nproc`
    # We need to put these things in a dedicated folder to avoid clashing with files of the same name in downstream projects.
    - mkdir core_artefacts
    - mv build cmake examples include src tests core_artefacts
  artifacts:
    when: always
    paths:
      # These are all the things required to install the full core.
      - core_artefacts/build/cmake_install.cmake
      - core_artefacts/build/coreDependencies.cmake
      - core_artefacts/build/qbcore-config.cmake
      - core_artefacts/build/qbcore-config-version.cmake
      - core_artefacts/build/CMakeFiles/Export/
      - core_artefacts/build/CITests
      - core_artefacts/build/lib*
      - core_artefacts/build/core.cpython-38-x86_64-linux-gnu.so
      - core_artefacts/build/plugins
      - core_artefacts/build/configured_example_files
      - core_artefacts/cmake/py_packages_path.cmake
      - core_artefacts/cmake/xacc_utilities.cmake
      - core_artefacts/cmake/manifest.json.in
      - core_artefacts/include
      - core_artefacts/examples
      - core_artefacts/src/aws_braket/aws_python_script.py
      - core_artefacts/tests/XaccInitialisedTests.cpp

ubuntu20-cpp-tests:
  stage: test
  needs: ["ubuntu20-build"]
  extends: .install-core
  image: $CI_IMAGE
  script:
    - ./build/CITests --test --gtest_output='xml:core_gtests.xml'
    - rm -rf ${QB_DIR}/core-local
  artifacts:
    when: always
    reports:
      junit: core_gtests.xml

ubuntu20-py-tests:
  stage: test
  needs: ["ubuntu20-build"]
  extends: .install-core
  image: $CI_IMAGE
  script:
    - cd tests/python_module && python3 -m pytest --junitxml="report.xml"
    - rm -rf ${QB_DIR}/core-local
  artifacts:
    when: always
    reports:
      junit: tests/python_module/report.xml

ubuntu20-py-stack-tests:
  stage: test
  needs: ["ubuntu20-build"]
  extends: .install-core
  image: $CI_IMAGE
  script:
    - echo "# QB_QCSTACK_2023_2_1_URL = $QB_QCSTACK_2023_2_1_URL"
    - cd tests/qcstack && python3 -m pytest --junitxml="report-stack.xml"
    - rm -rf ${QB_DIR}/core-local
  artifacts:
    when: always
    reports:
      junit: tests/qcstack/report-stack.xml

trigger-decoder:
  needs: ["ubuntu20-build"]
  stage: deploy
  trigger:
    project: qbau/software-and-apps/decoder  
    branch: main
  variables:
    UPSTREAM_REF: $CI_COMMIT_REF_NAME

trigger-emulator:
  needs: ["ubuntu20-build-for-emulator"]
  stage: deploy
  trigger:
    project: qbau/software-and-apps/emulator
    branch: main
  variables:
    UPSTREAM_REF: $CI_COMMIT_REF_NAME
