stages:
  - build

before_script:
  - echo $PWD
  - ls -l
  - whoami

ubuntu20.04:
  stage: build
  image: quantumbrilliance/ci-ubuntu20.04:sdk-beta-12
  script:
    - cmake -B build . -DTNQVM_DIR=${QB_DIR}/xacc-local
    - cmake --build build -- -j`nproc`
    - cmake --install build
