stages:
  - build
  - test

before_script:
  - echo $PWD
  - ls -l
  - whoami

ubuntu20-build:
  stage: build
  image: quantumbrilliance/ci-ubuntu20.04:sdk-beta-13
  script:
    - cmake -B build . -DTNQVM_DIR=${QB_DIR}/xacc-local
    - cmake --build build -- -j`nproc`
  artifacts:
    when: always
    paths:
      - build/CITests
      - build/cmake_install.cmake
      - build/core.cpython-38-x86_64-linux-gnu.so
      - build/lib*
      - build/plugins
      - build/configured_example_files

ubuntu20-cpp-tests:
  stage: test
  needs: ["ubuntu20-build"]
  image: quantumbrilliance/ci-ubuntu20.04:sdk-beta-13
  script:
    - cmake --install build
    - ./build/CITests --test --gtest_output='xml:core_gtests.xml'
  artifacts:
    when: always
    reports:
      junit: core_gtests.xml

ubuntu20-py-tests:
  stage: test
  needs: ["ubuntu20-build"]
  image: quantumbrilliance/ci-ubuntu20.04:sdk-beta-13
  script:
    - cmake --install build
    - cd tests/python_module && python3 -m pytest --junitxml="report.xml"
  artifacts:
    when: always
    reports:
      junit: tests/python_module/report.xml

ubuntu20-py-stack-tests:
  stage: test
  needs: ["ubuntu20-build"]
  image: quantumbrilliance/ci-ubuntu20.04:sdk-beta-13
  script:
    - cmake --install build
    - echo "# QB_QCSTACK_URL = $QB_QCSTACK_URL"
    - cd tests/qcstack && python3 -m pytest --junitxml="report-stack.xml"
  artifacts:
    when: always
    reports:
      junit: tests/qcstack/report-stack.xml

