variables:
  CI_IMAGE_UBUNTU_X86_CLANG: registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/ubuntu_x86-22.04:all_dep_clang-2
  CI_IMAGE_UBUNTU_X86_CLANG_CUDA: registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/ubuntu_x86-22.04:all_dep_cuda-12.1.1_clang-2
  CI_IMAGE_UBUNTU_X86_GCC: registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/ubuntu_x86-22.04:all_dep_gcc-2
  CI_IMAGE_RHEL_X86:  registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/rhel_x86-8:all_dep_cuda-12.1.1_clang-2
  CI_IMAGE_RHEL_PPC:  registry.gitlab.com/qbau/software-and-apps/ci-dockerfiles/rhel_ppc64le-8:all_dep_cuda-12.1.1_clang-2
